name: evolum_package
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_serializable: ^3.5.0
  cloud_firestore: ^0.14.2
  equatable: ^1.2.5
  splash_tap: ^0.1.2
  flutter_hooks: ^0.14.1
  intl: ^0.16.1
  build_runner: ^1.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter