name: evolum_package
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.14.3+1
  cloud_firestore_web: ^0.2.0+5
  
  json_serializable: ^3.5.0
  equatable: ^1.2.5
  splash_tap: ^0.1.2
  flutter_hooks: ^0.14.1
  intl: ^0.16.1
  copy_with_extension: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner: ^1.10.4
  copy_with_extension_gen: ^1.4.0
