name: evolum_package
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.14.3+1
  cloud_firestore_web: ^0.2.0+5
  
  json_serializable: ^3.5.0
  equatable: ^1.2.5
  splash_tap: ^0.1.2
  flutter_hooks: ^0.15.0
  intl: ^0.16.1
  copy_with_extension: ^1.4.0
  simple_animations: ^2.2.2
  lottie: ^0.7.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner: ^1.10.4
  copy_with_extension_gen: ^1.4.0

flutter:
  uses-material-design: true
  assets:
   - assets/image/background/
   - assets/image/icon/
   - assets/image/player/
   - assets/image/tab/
   - assets/image/download/
   - assets/image/gift/
   - assets/image/gift/white/
   - assets/image/gift/black/
   - assets/image/background/afternoon/
   - assets/image/background/sunset/
   - assets/image/background/daybreak/
   - assets/image/background/deepnight/
   - assets/image/background/earlynight/
   - assets/image/background/morning/
   - assets/image/background/noon/
   - assets/image/background/evening/
   - assets/image/share/
   - assets/image/drawing/big/white/
   - assets/image/drawing/big/black/
   - assets/image/drawing/small/white/
   - assets/image/drawing/small/black/
   - assets/image/sales/
   - assets/image/chakras/
   - assets/lottie/
   - assets/audio/
   - assets/video/
   - assets/video/background/


  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCerealLight.ttf
          weight: 300
        - asset: assets/fonts/AirbnbCerealBook.ttf
          weight: 400
        - asset: assets/fonts/AirbnbCerealMedium.ttf
          weight: 600
        - asset: assets/fonts/AirbnbCerealBold.ttf
          weight: 700
        - asset: assets/fonts/AirbnbCerealExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AirbnbCerealBlack.ttf
          weight: 900