name: evolum_package
description: all tools use for evolum flutter project
version: 3.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^4.9.3
  cloud_firestore_web: ^3.6.0
  cloud_firestore_odm: ^1.0.0-dev.69

  # Utils
  intl: ^0.18.0
  copy_with_extension: ^5.0.2
  json_annotation: 4.8.1
  http: ^0.13.4

  # UI/UX
  simple_animations: ^3.0.3
  lottie: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.3
  copy_with_extension_gen: ^5.0.2
  cloud_firestore_odm_generator: ^1.0.0-dev.58
  json_serializable: ^6.0.1

dependency_overrides:
  graphs: 2.2.0
  
flutter:
  uses-material-design: true
  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCerealLight.ttf
          weight: 300
        - asset: assets/fonts/AirbnbCerealBook.ttf
          weight: 400
        - asset: assets/fonts/AirbnbCerealMedium.ttf
          weight: 600
        - asset: assets/fonts/AirbnbCerealBold.ttf
          weight: 700
        - asset: assets/fonts/AirbnbCerealExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AirbnbCerealBlack.ttf
          weight: 900
